### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by nobilislux** [dkoen/crary-lab-classifier#4]
Complete excel sheet with digital data from PIP
Transfer coordinates to the drive from PIP to the hard drive/ mybook
Build false positive annotations in PIP 
Chalk out a plan to build collaboration with volunteer

**Comment by dkoen** [comment]
making this into smaller issues. 

Complete excel sheet with digital data from PIP: 
https://github.com/dkoen/crary-lab-classifier/issues/5 

Transfer coordinates to the drive from PIP to the hard drive/ mybook: 
https://github.com/dkoen/crary-lab-classifier/issues/6

Build false positive annotations in PIP: 
https://github.com/dkoen/crary-lab-classifier/issues/7

Chalk out a plan to build collaboration with volunteer: 
https://github.com/dkoen/crary-lab-classifier/issues/8
